### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Spudley** [ireade/inlinetweetjs#2]
Hi.

Can you specify the license for this script, please? I am unable to use it unless I can be certain that it is licensed in a way that is compatible with the rest of my site.

Thank you.

**Comment by ireade** [comment]
Hey @Spudley ! I've added that now, see the README

**Comment by Spudley** [comment]
Awesome, thank you. :)

By the way, if you add the GPL license file to your repo as a file called LICENSE, then GitHub will be able to automatically know which license you're using as well.
